### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by venelink** [kawine/dataset_difficulty#1]
Hi,

It seems that requirements.txt is created from conda rather than from pip (https://stackoverflow.com/questions/48787250/set-up-virtualenv-using-a-requirements-txt-generated-by-conda)

Installing it with pip install -r requirements.txt throws an errorr (Hint: = is not a valid operator. Did you mean == ?)

Could you please provide the file generated using pip freeze

Thanks.

**Comment by kawine** [comment]
I've updated the requirements.txt file to work with pip and also added a setup.sh file. Let me know if you're still having issues!
