### ISSUE TITLE
Error with python augment.py --raw_data_dir RAW_DATA_DIR

### ISSUE THREAD

**Issue by khareyash05** [kawine/dataset_difficulty#3]
Hi I am facing this problem  when i type 
```
python augment.py --raw_data_dir RAW_DATA_DIR
```
![image](https://user-images.githubusercontent.com/60147732/184537547-6cd34f4c-12d5-419b-90ad-167ba105d7df.png)
Please help! Thanx!

**Comment by kawine** [comment]
You need to specify a directory that exists. e.g., create a local directory named 'local_data' and then run 
`python augment.py --raw_data_dir ./local_data`
