### ISSUE TITLE
Can PVI be used to measure usable information for non classification tasks, i.e., data reconstruction, object detection, etc,.

### ISSUE THREAD

**Issue by Zmjcc** [kawine/dataset_difficulty#5]
PVI provides a convenient  way to measure the difficulty of each instance in the dataset, but the calculation of usable information used seems to be only applicable for classification tasks? Can you provide some ideas for measuring the difficulty level of datasets in other tasks?

**Comment by kawine** [comment]
Great question! I think the most straightforward way of doing this is by discretizing the output distribution. 

For example, in the MAUVE paper, Pillutla et al discretize text by doing k-means clustering on language model embeddings of the text. They used that to turn a document of sentences into a distribution over K clusters.

To understand difficulty, you could use the same technique to create pseudo-classes that you can use V-info with. As K approaches infinity, each datapoint becomes its own pseudoclass.
